package com.happyfiit.android;

import android.app.Application;


import com.happyfiit.android.sdk.ApplicationConfig;
import com.happyfiit.android.sdk.FirstRunHandler;
import com.happyfiit.android.sdk.Happyfiit;
import com.happyfiit.android.sdk.Opportunity;
import com.happyfiit.android.sdk.Workout;

import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


public class SampleApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        Map<String, String> initParams = new HashMap<>();

        // Mandatory
        initParams.put(ApplicationConfig.DEVELOPER_KEY, "test_user_key");
        initParams.put(ApplicationConfig.DEVELOPER_SECRET, "jDQpJea7klf7fT6y7jk821pHu2m2461U");

        // Optional
        //
        // If possible then provide the user's email address to help happyfiit identify him across different
        // installations and mobile devices.
        // Otherwise a unique id will be generated by Happyfiit and used throughout this application installation only.
        // initParams.put(ApplicationConfig.USER_EMAIL, "user@gmail.com");

        // Initialize (A)
        Happyfiit.initialize(getApplicationContext(), initParams);

        // Initialize (B)
        // Use the function below to additionally provide user's historic data.
        //Happyfiit.initialize(getApplicationContext(), initParams, firstRunHandler());
    }


    private FirstRunHandler firstRunHandler() {
        return new FirstRunHandler() {
            @Override
            public Opportunity getWorkoutHistory() {

                //create user's workout history

                Workout workout1 = new Workout.Builder()
                        .type("running")
                        .addWorkoutStatistic("distance", "meter", 100)
                        .addWorkoutStatistic("duration", "sec", 10)
                        .addWorkoutStatistic("avg. speed", "km/h", new Double(100 / 10))
                        .time(new DateTime(2015, 3, 26, 18, 0, 20))
                        .build();

                Workout workout2 = new Workout.Builder()
                        .type("running")
                        .addWorkoutStatistic("distance", "meter", 100)
                        .addWorkoutStatistic("duration", "sec", 9)
                        .addWorkoutStatistic("avg. speed", "km/h", new Double(100 / 9))
                        .time(new DateTime(2015, 3, 10, 18, 0, 0))
                        .build();

                List<Workout> workouts = new ArrayList<>(Arrays.asList(workout1, workout2));

                Opportunity op = new Opportunity.Builder()
                        .history(true)
                        .addWorkoutList(workouts)
                        .addParameter("pb", 10)
                        .build();

                return op;
            }
        };
    }
}